export const questions = [
  'Vous attrapez le nouveau variant du Coronavirus… Quels sont ses symptômes ? (du moins grave au plus préoccupant)',
  "Vous devez cuisiner pour un dîner important… Complétez, de 'le pire désastre culinaire imaginable' à 'le repas digne d’un restaurant étoilé'.",
  'Vous découvrez une porte secrète chez vous que vous n’aviez jamais vue… Où mène-t-elle ? (de la pire destination à la meilleure)',
  'Vous êtes recruté par une organisation secrète… Quel objectif cherche-t-elle à atteindre ? (du pire au meilleur)',
  'Vous achetez un objet sur Internet et recevez un objet qui n’a rien à voir… Que recevez-vous ? (du pire au meilleur)',
  'Un sorcier vous transforme en un objet de la maison… En quoi êtes-vous transformé ? (du pire au meilleur)',
  'Vous découvrez un pouvoir magique que vous possédez soudainement… Quel est-il ? (du pire au meilleur)',
  'Vous vous réveillez un matin et découvrez que vous avez échangé votre corps avec une célébrité… Qui est-ce ? (du pire au meilleur)',
  'Vous êtes invité à passer une journée avec une célébrité… Avec qui ? (du pire au meilleur)',
  'Une rumeur circule à votre sujet dans votre ville… Quelle est cette rumeur ? (de la pire à la meilleure)',
  'Vous êtes le méchant du prochain Batman… Quel est votre plan diabolique ? (du plus pitoyable au plus exceptionnel)',
  'Un voyageur temporel arrive et vous révèle votre destin… Qu’apprenez-vous ? (de la pire nouvelle à la meilleure prédiction)',
  'Vous devenez le dirigeant d’un pays ou d’une contrée (réel ou fictif)… Lequel ? (du pire au meilleur)',
  'Vous êtes choisi pour tester une nouvelle technologie futuriste… Quelle est cette technologie et que se passe-t-il ? (du plus décevant au plus révolutionnaire)',
  'Un esprit malin vous possède pour une journée… Que faites-vous sous son contrôle ? (de la pire connerie au plus fantastique exploit)',
  'Vous devez écrire votre autobiographie… Quel est le titre de votre livre ? (du pire au meilleur)',
  'Vous participez à une émission de télé-réalité complètement absurde… Quelle est l’idée de l’émission ? (de la pire à la… moins pire)',
  'Vous êtes enfermé dans un jeu vidéo pour toujours… Dans lequel ? (du pire au meilleur)',
  'Vous devenez l’auteur d’une citation célèbre… Quelle est cette phrase mémorable ? (de la plus neuneu à la plus inspirante)',
  'Vous créez une secte (ou un mouvement)… Quel est son credo ? (du pire au meilleur)',
  'Vous vous réveillez un lendemain de cuite avec un tatouage tout neuf… Qu’est-ce qu’il représente ? (du pire au meilleur)',
  'Vous passez tous un weekend ensemble… Que faites-vous (du plus ennuyeux au plus passionnant)',
  'Vous êtes invité à un dîner où tout le monde doit venir déguisé… En quoi vous déguisez-vous ? (du déguisement mémorable pour de mauvaises raisons à celui mémorable pour de bonnes raisons)',
  'Une énorme tempête vous propulse dans une époque différente… Où arrivez-vous et que faites-vous ? (du plus ennuyeux au plus passionnant)',
  'Vous inventez un parfum qui devient un best-seller… Quelle en est la senteur ? (du plus repoussant au plus envoûtant)',
  'Les aliens décident que vous êtes le plus digne représentant de l’humanité. Pourquoi ? (de la pire raison à la meilleure)',
  'Vous écrivez une loi qui sera appliquée dans le monde entier… Quelle est cette loi ? (de celle qui fera du monde un enfer à celle amènera la paix pour tous)',
  'Vous trouvez une lampe magique… Quel est votre premier vœu ? (du plus catastrophique au plus génial)',
  'Vous découvrez que votre animal de compagnie peut parler… Que dit-il ? (de l’anecdote la plus gênante au discours le plus élogieux)',
  'Une ville entière est renommée en votre honneur… Quelle est cette ville et pourquoi celle-ci ? (de la plus improbable à la plus prestigieuse)',
  'Vous êtes le prochain invité d’un podcast mondialement connu… Quel sujet abordez-vous ? (du plus ridicule au plus passionnant)',
  'Un super-héros vous emploie pour être son stagiaire… Quelle est votre mission ? (du plus absurde au plus honorable)',
];
